---
- hosts: "{{host|default('web3')}}"
  gather_facts: False
  vars_files:
    - role_vars.yml
  tasks:
    - name: get push env  # 獲取推送環境
      shell: echo $HOSTNAME | sed -n 's/.*\.\([^\/]*\)$/\1/p'
      register: env
    - name: document root (qa) # 文檔根 (qa)
      shell: "readlink /home/ci-user/www/{{item.1}}/current"
      register: qa_directory
      with_together:
        - "{{role}}"
        - "{{docroot}}"
      when: env.stdout == 'qa'
      run_once: true
    - name: document root (prod)  # 文檔根 (prod)
      shell: "readlink /home/rd6-admin/www/{{item.1}}/current"
      register: prod_directory
      with_together:
        - "{{role}}"
        - "{{docroot}}"
      when: env.stdout == 'prod'
      run_once: true
    - debug:
        msg: "{{item.0}} => {{item.1}}"
      with_together:
        - "{{qa_directory.results | map(attribute='cmd') | list}}"
        - "{{qa_directory.results | map(attribute='stdout_lines') | list}}"
      when: env.stdout == 'qa'
      run_once: true
    - debug:
        msg: "{{item.0}} => {{item.1}}"
      with_together:
        - "{{prod_directory.results | map(attribute='cmd') | list}}"
        - "{{prod_directory.results | map(attribute='stdout_lines') | list}}"
      when: env.stdout == 'prod'
      run_once: true