---
- name: 'git clone'
  hosts: localhost
  gather_facts: false
  vars_files:
    - role_vars.yml
  tasks:
    - name: 'git clone'
      git:
        repo: 'ssh://git@gitlab-pid.vir888.com:10022/wells_lin/{{ project }}.git'
        dest: '/home/ci-user/wells_lin/{{item.1}}/release/{{ tag }}'
        clone: yes
        update: no
        version: "{{ tag }}"
      with_together:
        - "{{role}}"
        - "{{docroot}}"
- name: '部署檔案'
  hosts: '{{ host }}'
  gather_facts: false
  remote_user: ci-user
  vars_files:
    - role_vars.yml
  tasks:
    - name: '文件複製到test測試機'
      synchronize:
        src: "/home/ci-user/wells_lin/{{item.1}}/release/{{ tag }}"
        dest: "/home/ci-user/wells_lin/{{item.1}}/release/"
      with_together:
        - "{{role}}"
        - "{{docroot}}"
    - name: '更新 current 指向'
      shell: cd wells_lin/{{item.1}} &&  ln -snf release/{{ tag }} current
      with_together:
        - "{{role}}"
        - "{{docroot}}"
      
    







# ansible test* -m shell -a "ls /home/ci-user/wells_lin/docker-compose-nginx-php/release"
# ansible test* -m shell -a "ls -lr /home/ci-user/wells_lin/docker-compose-nginx-php"
# ansible test* -m shell -a "curl http://localhost:8082"

# ansible-playbook /home/ci-user/wells_lin/current_new.yaml -e project=web/bin/fe_admin -e host=web1
# ansible test* -a hostname
# ansible test* -m synchronize -a "src=/home/ci-user/wells_lin/docker-compose-nginx-php dest=/home/ci-user/wells_lin/"
# docker-compose -f /home/ci-user/wells_lin/docker-compose-nginx-php/current/docker-compose.yaml restart



cd -P current/
docker inspect wells-nginx-server