--- 
- name: '切換版本'
  hosts: localhost
  gather_facts: false
  vars:
    git_dir: /home/ci-user/wells_lin/git
  tasks:
    - name: '切換版本'
      shell: cd {{ git_dir }} && git checkout {{ tag }}
- name: '部署檔案'
  hosts: '{{ host }}'
  gather_facts: false
  remote_user: ci-user
  vars:
    git_dir: /home/ci-user/wells_lin/git
  tasks:
    - name: '文件複製到test測試機'
      copy:
        src: "{{ git_dir }}"
        dest: "/home/ci-user/wells_lin/"